### PR TITLE
Tradução pt-br

### PR DESCRIPTION
**Pull request by Phoenixx1202**

### CODE REVIEW

**Comment by bucanero** [comment]
@Phoenixx1202 , only the `pkgfiles/USRDIR/LANG/pt.po` file is needed, you can remove the other.

@jsds96 @jhonathanc as I don't know Portuguese, could you guys take a look?

**Comment by jsds96** [comment]
@bucanero I looked line by line in the file comparing it to the translation I sent earlier.
And @Phoenixx1202's translation is a copy of what I sent.
The only differences that appear in the file were the change of the beginning of each word to capital letter (_incorrect for our grammar_) and the removal of some accents.

**Comment by jhonathanc** [comment]
Sorry, I'm late to the party. I discovered my wife is pregnant some days ago and didn't have enough time :D.

About the ABNT, it's not necessary to follow it but it's prefererable since it's a standard.

I will take a look at the translations tonight, but if two translators agreed with the translations at the point of only some capital letters and/or accents is different, it means the translation is very good.

**Comment by jhonathanc** [comment]
I checked both, and the @jsds96 looks more "polished". And I agree with him, capital letters without any rule looks really weird.

**Pull request merged**
