### PR TITLE
Polish translation improvements

### PR DESCRIPTION
**Pull request by olokos**
Mostly grammar updates, making it more clear and look more official, by using less colloquial words. In some places I made it more understandable and true to original. The most striking thing in previous translations is "Free" translated as "Free to download" not as "Free space" meaning. I'm not sure if I should change the last translator on top, but I updated the revision date and filled the translators as they are now on the bottom.

### CODE REVIEW

**Comment by olokos** [comment]
```
#: pkgi.c:122
msgid "Task successfully queued (reboot to start)"
msgstr "Zadanie pomyslnie umieszczone w kolejce (uruchom ponownie, aby rozpoczac)"
```

I'm not sure what to do about this, which is also a bit bothering, since the screen only displays around `Zadanie pomyslnie umieszczone w kolejce (uruchom` - the rest is cut off, can we do `umieszczone w kolejce \n (uruchom`?

**Review by PoliPyc — APPROVED** [review]
Hey, awesome fixes. I have to admit I did one of language updates before and did one of the worst things i could.
I trusted my predecessor with language context and only improved his version not actually checking if words makes sense.
It did bother me for a long time great that you fixed that

**Comment by PoliPyc** [comment]
> ```
> #: pkgi.c:122
> msgid "Task successfully queued (reboot to start)"
> msgstr "Zadanie pomyslnie umieszczone w kolejce (uruchom ponownie, aby rozpoczac)"
> ```
> 
> I'm not sure what to do about this, which is also a bit bothering, since the screen only displays around `Zadanie pomyslnie umieszczone w kolejce (uruchom` - the rest is cut off, can we do `umieszczone w kolejce \n (uruchom`?

How about: `Zadanie umieszczone w kolejce \n (Zrestartuj, aby rozpoczac)` ?

**Review by PoliPyc — APPROVED** [review]

**Comment by olokos** [comment]
I'm amazed by such a quick reply and great work before, thank You!

I did have a look on the console and on 2 occasions I also looked into pkg-i source code to see what the line really means 😄 
If `\n` works by creating a new line below, we could even perhaps have it `Zadanie umieszczone w kolejce \n (Zrestartuj konsolę, aby rozpoczac)` which means `Task successfully placed into queue \n (Restart the console, to begin)`?

**Comment by olokos** [comment]
So I just tested this on the console, and `kolejce \n (Zrestartuj` just prints `\n` without a newline.
On the positive side, the text for that line is short enough to fit on the screen, without breaking through the gray box, after my recent changes, so we don't really need the newline anymore!
In this situation, I think this is the best solution and I'd say it's ready for merge!

**Comment by bucanero** [comment]
Just for reference, the latest 1.2.4 version should adjust the Settings menu width based on the text length.

So if you need to use longer text for the Settings options (when you open with `Triangle`) , feel free to edit the translation and test.

If not needed, let me know and I'll just merge this PR.

**Comment by olokos** [comment]
The `Zadanie umieszczone w kolejce \n (Zrestartuj konsole, aby rozpoczac)` still overflows through the right side of the grey rectangle, on the `task added successfully` screen, if it's too long.

The settings right side panel does seem to scale, but only for the initial draw.
I have planned to make it:
`Pobieraj w tle` - Download in the background
`Pobieraj bezpośrednio` - Download directly

If PKGi launches with "Pobieraj w tle` and I switch to `Pobieraj bezpośrednio`, then after switching to the bg download, the writing will still go through the rectangle grey box and off the screen, same way as in "task added successfully" screen, as the settings sidebar is scaled only for max width of `Pobieraj w tle`.

I've also been thinking, to perhaps use polish diacritic characters, since PS3 does originally include polish language with polish diacritic characters, such as `Zażółć gęślą jaźń` - This word makes almost no sense, but contains all the diacritic characters.

Would it be possible to include the diacritic characters somehow aswell?

**Comment by bucanero** [comment]
> The `Zadanie umieszczone w kolejce \n (Zrestartuj konsole, aby rozpoczac)` still overflows through the right side of the grey rectangle, on the `task added successfully` screen, if it's too long.

Currently there's no auto-size adjustment on the message boxes. So for those strings you need to consider string lengths.

> If PKGi launches with "Pobieraj w tle`and I switch to`Pobieraj bezpośrednio`, then after switching to the bg download, the writing will still go through the rectangle grey box and off the screen, same way as in "task added successfully" screen, as the settings sidebar is scaled only for max width of `Pobieraj w tle`.

Yes, the "Settings" menu width is calculated with the current option, so like you said when switching the next option could end up out of border. (but if you save settings and re-open the menu, it should show up correctly)
I guess it's a bug/improvement to fix in a future version. 

> 
> I've also been thinking, to perhaps use polish diacritic characters, since PS3 does originally include polish language with polish diacritic characters, such as `Zażółć gęślą jaźń` - This word makes almost no sense, but contains all the diacritic characters.
> 
> Would it be possible to include the diacritic characters somehow aswell?

Right now the app uses a standard ASCII font (256 characters) for the settings, message boxes and other text elements. So only characters available on the default ASCII charset can be used. 
For reference you can check the complete ASCII set here: https://theasciicode.com.ar/

**Pull request merged**
