### PR TITLE
Fixed code for compiling in Windows

### PR DESCRIPTION
**Pull request by blckbearx**
All the stuff we talked on PSX-Place :)

### CODE REVIEW

**Comment by bucanero** [comment]
thanks! I'll check the changes on my side and let you know

**Comment by juanmarquezruiz** [comment]
> Todo lo que hablamos en PSX-Place :)

podría dejar la flojera y por lo menos pegar aquí la charla y así tener información sobre cambios o ideas o comentarios aplicados en el código que publica??

**Comment by blckbearx** [comment]
If you take a look at the changes you'll notice that I've commented out some duplicate definitions so the windows compiler doesn't complain. There's nothing more to it.

I know that I wasn't explicit about the changes but it was simple stuff that bucanero himself could have fixed and it doesn't change the final software, that's why I didn't explain.

**Comment by bucanero** [comment]
@blckbearx , sorry for not merging, I was adding a lot of stuff on my side and I didn't had a chance to do it.
Now to avoid merge conflicts, I'm going to remove those duplicate struct definitions and changes on my side, commit it to master, and if you have a chance I'll ask to check to compile and see if it's fixed for good.

**Comment by blckbearx** [comment]
No problem! I guessed that with all the changes it would take more time, I'll be here ready to test it when you update.

**Comment by bucanero** [comment]
hey @blckbearx ,
I didn't forget about this. :) 
I have built a virtual machine with Windows 7, and recreated a clean ps3-dev environment in the VM using @Estwald [PSDK3v2](https://github.com/Estwald/PSDK3v2).

Now I'll just clone the repo, try to include your changes and compile it. If everything works, I'll merge the changes back to the main repository.

**Comment by bucanero** [comment]
@blckbearx 
I've committed the changes directly to the main branch ( https://github.com/bucanero/pkgi-ps3/commit/40c58a26a70e0d80a78b5ed22eef9567239c3873 )

I'm closing the PR, I've tested on my virtual machine  with PSDK3v2 and I was able to compile the app without issues. Let me know if you find any issue building the master branch.

thanks for your help!

**Pull request closed without merging**
